blank_issues_enabled: true
contact_links:
  - name: Cyberparadism Manifesto
    url: https://zarazinsfuss.github.io/cyberparadism/manifesto/
    about: Read the Cyberparadism Manifesto for inspiration
  - name: Aesthetics Wiki
    url: https://personal-aesthetics.fandom.com/wiki/Cyberparadism
    about: Learn more about Cyberparadism on the Aesthetics Wiki
